name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  shared_preferences: ^0.5.12+4
  fluttertoast: ^7.1.5
  cached_network_image: ^2.4.1
  firebase_messaging: 7.0.0
  firebase_storage: ^4.0.0
  image_picker: ^0.6.7+14
  flutter_local_notifications: 1.4.4+4
  photo_view: ^0.10.2
  firebase_core: "0.5.2+1"
  modal_progress_hud: ^0.1.3
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  animated_text_kit: ^1.3.0
  auto_size_text: ^2.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
